/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parse.response.to.json.example;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
